name       : kross
version    : 5.43.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/portingAids/kross-5.43.0.tar.xz : d0900a7d953e49fd68741ce20eaf57f3242b3ca186debc2ed0ca68ad2b31fd16
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Embedding of scripting into applications
description: |
    The Kross scripting framework provides full Python, Ruby and KDE JavaScript scripting support. The goal was to limit the work needed on applications to have them fully scriptable and to provide a modular way to transparently integrate additional interpreters and in that way extend your application with a new scripting-backend without any new line of code and even without any recompile.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
rundeps    :
    - devel :
        - ki18n-devel
        - kiconthemes-devel
        - kio-devel
        - kparts-devel
        - kwidgetsaddons-devel
        - qt5-script-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
