name       : kross
version    : 5.56.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/portingAids/kross-5.56.0.tar.xz : bbfafe4abd2c2166f31eb36daa1849f4dc4a829c06fe85402e1fad0ce875c667
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Embedding of scripting into applications
description: |
    The Kross scripting framework provides full Python, Ruby and KDE JavaScript scripting support. The goal was to limit the work needed on applications to have them fully scriptable and to provide a modular way to transparently integrate additional interpreters and in that way extend your application with a new scripting-backend without any new line of code and even without any recompile.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
rundeps    :
    - devel :
        - ki18n-devel
        - kiconthemes-devel
        - kio-devel
        - kparts-devel
        - kwidgetsaddons-devel
        - qt5-script-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
