name       : kross
version    : 5.105.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/portingAids/kross-5.105.0.tar.xz : e54b1ec87296d7cf4ecabe82124be33a1704de370545dbc103c47df9434337fa
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Embedding of scripting into applications
description: |
    The Kross scripting framework provides full Python, Ruby and KDE JavaScript scripting support. The goal was to limit the work needed on applications to have them fully scriptable and to provide a modular way to transparently integrate additional interpreters and in that way extend your application with a new scripting-backend without any new line of code and even without any recompile.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kiconthemes-devel
    - kparts-devel
rundeps    :
    - devel :
        - kiconthemes-devel
        - kparts-devel
        - qt5-script-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
