name       : kross
version    : 5.38.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.38/portingAids/kross-5.38.0.tar.xz : 670dc18d258e8f821fcd64ba30c587ac3afaecbc54d968edb0fe624682788cb5
license    : LGPL-2.1
component  : programming
summary    : Embedding of scripting into applications
description: |
    The Kross scripting framework provides full Python, Ruby and KDE JavaScript scripting support. The goal was to limit the work needed on applications to have them fully scriptable and to provide a modular way to transparently integrate additional interpreters and in that way extend your application with a new scripting-backend without any new line of code and even without any recompile.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
rundeps    :
    - devel :
        - ki18n-devel
        - kiconthemes-devel
        - kio-devel
        - kparts-devel
        - kwidgetsaddons-devel
        - qt5-script-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
