name       : kross
version    : 5.53.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/portingAids/kross-5.53.0.tar.xz : 5e7ef96c1c981d8c47928301eb1c84d69c1567ae46cf716275b2765befbdc9e0
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Embedding of scripting into applications
description: |
    The Kross scripting framework provides full Python, Ruby and KDE JavaScript scripting support. The goal was to limit the work needed on applications to have them fully scriptable and to provide a modular way to transparently integrate additional interpreters and in that way extend your application with a new scripting-backend without any new line of code and even without any recompile.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
rundeps    :
    - devel :
        - ki18n-devel
        - kiconthemes-devel
        - kio-devel
        - kparts-devel
        - kwidgetsaddons-devel
        - qt5-script-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
