name       : kross
version    : 5.66.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/portingAids/kross-5.66.0.tar.xz : 109159996da54ec52ec8114ff05f88bdee6428e49ca84515ab73c457e0005ebc
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Embedding of scripting into applications
description: |
    The Kross scripting framework provides full Python, Ruby and KDE JavaScript scripting support. The goal was to limit the work needed on applications to have them fully scriptable and to provide a modular way to transparently integrate additional interpreters and in that way extend your application with a new scripting-backend without any new line of code and even without any recompile.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
rundeps    :
    - devel :
        - ki18n-devel
        - kiconthemes-devel
        - kio-devel
        - kparts-devel
        - kwidgetsaddons-devel
        - qt5-script-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
